name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Package Lambda
      run: |
        mkdir package
        cp -r src package/
        cd package
        zip -r ../deployment-package.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name my-anomaly-detector \
          --zip-file fileb://deployment-package.zip
